# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95f11394a65ae3056d1f5a61b4032d91ec61ba988e784728e643309a14c4af402040b5873d438f02e9997c6de01c007428966dd18d36a7882abae3ab8277f1e0

test:
  secret_key_base: 303fadf2646d4874fce0cfa2be500fb7a6c230c8378a29fee017046be98def0cb9e6b51eb734ba074e6156d81177ff11859a7cdaa201e5f3a4498e07e0c6eb72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
